// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "CoreMinimal.h"
#include "FABaseCharacter.h"
#include "WorldMap/MapNode.h"
#include "LocationInfo.generated.h"

/**
 * 
 */
UCLASS(BlueprintType, EditInlineNew)
class FLIGHTATTENDANTSIM_API ULocationInfo : public UObject
{
	GENERATED_BODY()

public:
	// The display name of the location
	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, SaveGame)
	FText LocationName;
	
	// Facilities situated on the location
	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, SaveGame)
	TArray<TEnumAsByte<EFacilityType>> Facilities;
	
	// Characters currently situated on this location
	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, SaveGame)
	TArray<TAssetSubclassOf<AFABaseCharacter>> ResidentsCharacters;
	
	// Corresponding map node which is generated by MapGraph
	UPROPERTY(BlueprintReadOnly)
	UMapNode* CorrespondingNode = nullptr;

	void Merge(ULocationInfo* Other);

private:
	template<class T>
	static void MergeUnique(TArray<T>& A, const TArray<T>& B);
};
