// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "CoreMinimal.h"
#include "FABaseCharacter.h"
#include "WorldMap/MapNode.h"
#include "LocationInfo.generated.h"

class UCharacterInfo;

/**
 * 
 */
UCLASS(BlueprintType, EditInlineNew)
class FLIGHTATTENDANTSIM_API ULocationInfo : public UObject
{
	GENERATED_BODY()

public:
	// The display name of the location
	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly)
	FText LocationName;
	// TODO: Fix duplication of facilities list in MapNode.h
	// Facilities situated on the location
	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly)
	TArray<TEnumAsByte<EFacilityType>> Facilities;
	// Characters currently situated on this location
	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly)
	TArray<TAssetSubclassOf<AFABaseCharacter>> ResidentsCharacters;
	// Corresponding map node which is generated by MapGraph
	UPROPERTY(BlueprintReadOnly)
	UMapNode* CorrespondingNode = nullptr;
};
